version: "2.2"
services:
  redis:
    image: redis
  db: 
   image: postgres
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres

  vote:
    image: voting-app
    ports:
        - 8000:80


  worker:
    image: worker-app


  result: 
    image: result-app
    ports:
        - 8001:80    
